stages:
  candidates:
    cmd: python pipelines/candidates.py
    deps:
      - pipelines/candidates.py
      - data/lookup_party.csv
    outs:
      - data/candidates.csv:
          cache: false
      - src/_data/party_summary.json:
          cache: false

  notional:
    cmd: python pipelines/notional.py
    deps:
      - pipelines/notional.py
    outs:
      - src/_data/notional.json:
          cache: false
  results:
    # frozen: true
    cmd: python pipelines/results.py
    deps:
      - pipelines/results.py
      - data/candidates.csv
  
  thumbnails:
    frozen: true
    cmd: python pipelines/thumbnails.py
    deps:
      - pipelines/thumbnails.py
      - data/candidates.csv
    outs:
      - data/thumbnails.json:
          cache: false
    