// Press Association codes from https://election.pressassociation.com/general-election/general-election-2024/
// Colours from our 2019 results
export default {
  con: {
    name: "Conservative and Unionist Party",
    pa: "Con",
    colour: "#0485A8",
  },
  lab: {
    name: "Labour Party",
    pa: "Lab",
    colour: "#DC4343",
  },
  green: {
    name: "Green Party",
    pa: "Green",
    colour: "#5EBD4C",
  },
  ld: {
    name: "Liberal Democrats",
    pa: "LD",
    colour: "#EAA544",
  },
  ref: {
    name: "Reform UK",
    pa: "Reform",
    colour: "#09d2e0",
  },
  snp: {
    name: "Scottish National Party",
    pa: "SNP",
    colour: "#EBDB1C",
  },
  pc: {
    name: "Plaid Cymru",
    pa: "PC",
    colour: "#4FBA7C",
  },
  ukip: {
    name: "UK Independence Party",
    pa: "UKIP",
    colour: "#73537A",
  },
  dup: {
    name: "Democratic Unionist Party",
    pa: "DUP",
    colour: "#BF3759",
  },
  uup: {
    name: "Ulster Unionist Party",
    pa: "UUP",
    colour: "#3b75a8",
  },
  sdlp: {
    name: "Social Democratic and Labour Party",
    pa: "SDLP",
    colour: "#53BC5B",
  },
  alba: {
    name: "Alba",
    pa: "Alba",
    colour: "#0015ff",
  },
  wpb: {
    name: "Workers Party of Britain",
    pa: "WPB",
    colour: "#539acb",
  },
  sf: {
    name: "Sinn Féin",
    pa: "SF",
    colour: "#2C604D",
  },
  alliance: {
    name: "Alliance",
    pa: "Alliance",
    colour: "#EAA544",
  },
  apni: {
    name: "Alliance",
    pa: "Alliance",
    colour: "#EAA544",
  },
  tuv: {
	name: "Traditional Unionist Voice",
	pa: "TUV",
	colour: "#6dcad2"
  },
  other: {
    name: "Other",
    pa: "Other",
    colour: "#440d54",
  },
  speaker: {
    name: "Speaker seeking re-election",
    pa: "Speaker",
    colour: "#909090",
  },
  none: {
    name: "Not yet declared",
    pa: "TBD",
    colour: "#dfdfdf",
  },
  //
  //	 "brexit": "#0FA697",
  //	 "ind": "#CCA7C6",
  //	 "xspeaker": "#909090",
  //	 "monster": "#cccccc",
  //	 "none": "#dfdfdf",
  //
  /*
		"Abolish the Welsh Assembly Party": "Abolish",
		"Alliance for Democracy and Freedom": "ADF",
		"Alliance for Green Socialism": "Green Soc",
		"Animal Welfare Party": "AWP",
		"Aontu": "Aontu",
		"Ashfield Independents": "Ashfield",
		"Blue Revolution": "Blue",
		"British Democratic Party": "BDP",
		"British Unionist Party": "BUP",
		"Chesterfield Independents": "Chesterfield",
		"Christian Party": "Christian",
		"Christian Peoples Alliance": "CPA",
		"Climate": "Climate",
		"Communist Future": "Comm Future",
		"Communist League": "Comm Lge",
		"Communist Party of Britain": "Comm Brit",
		"Confelicity": "Confelicity",
		"Consensus": "Consensus",
		"Count Binface Party": "Binface",
		"Cross-Community Labour Alternative": "CCLA",
		"Democracy for Chorley": "Chorley",
		"English Constitution Party": "ECP",
		"English Democrats": "Eng Dem",
		"Fairer Voting Party": "FVP",
		"Freedom Alliance": "FA",
		"Hampshire Independents": "HampInd",
		"Heritage Party": "Heritage",
		"Independence for Scotland": "Ind Scot",
		"Independents for Direct Democracy": "IDD",
		"Kingston Independent Residents Group": "KIRG",
		"Liberal": "Lib",
		"Libertarian Party": "Libertarian",
		"Lincolnshire Independents": "Lincs",
		"Liverpool Community Independents": "LCI",
		"Monster Raving Loony Party": "Loony",
		"National Health Action Party": "NHAP",
		"New Open Non-Political Organised Leadership": "NonPol",
		"One Leicester": "One Leicester",
		"Party of Women": "PartyWomen",
		"People Before Profit": "PBP",
		"Portsmouth Independent Party": "Portsmouth",
		"Propel": "Propel",
		"Psychedelic Future Party": "PFP",
		"Putting Crewe First": "Crewe",
		"Rebooting Democracy": "Rebooting",
		"Rejoin EU": "Rejoin",
		"Save Us Now": "Save",
		"Scottish Christian Party": "SCP",
		"Scottish Family Party": "Scot Family",
		"Scottish Libertarian Party": "SLP",
		"Scottish Socialist Party": "SSP",
		"Shared Ground": "SG",
		"Social Democratic Party": "Soc Dem",
		"Social Democratic &amp; Labour Party": "Soc Dem",
		"Social Justice Party": "SJP",
		"Socialist Equality": "Soc Eq",
		"Socialist Labour Party": "Soc Lab",
		"Socialist Party of Great Britain": "SPGB",
		"South Devon Alliance": "Devon",
		"Sovereignty": "Sovereignty",
		"Stockport Fights Austerity No to Cuts": "Stockport",
		"Swale Indpendents": "Swale",
		"Taking The Initiative Party": "TTIP",
		"The Common Good": "Good",
		"The Common People": "People",
		"The Mitre TW9": "Mitre",
		"The North East Party": "NE Party",
		"The Peace Party": "Peace",
		"The Speaker": "Speaker",
		"speaker": "Speaker",
		"The Yorkshire Party": "Yorkshire",
		"The Yoruba Party in the UK": "Yoruba",
		"Trade Unionist and Socialist Coalition": "TUSC",
		"Traditional Unionist Voice": "TUV",
		"Transform": "Transform",
		"True & Fair": "True",
		"UK Voice": "Voice",
		"Volt": "Volt",
		"Women’s Equality Party": "Women",
		"Workers’ Revolutionary Party": "WRP",*/
};
